# Generated by Django 3.1.5 on 2021-05-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Addname',
        ),
    ]
